name: Reporting Bug
description: Report us the issue, and leave it to us! 🤗
title: "Bug: "
labels: "bug"
assignees: "USERSATOSHI,Leref"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Fill in the blanks by following the steps. 🙌
      
  - type: dropdown
    id: type
    attributes:
      label: Bug Type
      description: Please select a type of bug you want to report.
      options:
        - Classes 
        - Client 
        - Events 
        - Plugins 
        - Request
        - Websocket
    validations:
      required: true
      
  - type: textarea
    id: code
    attributes:
      label: reproducible code
      render: js
      description: Please send the minimum steps to reproduce this error
    validations:
      required: true
   
  - type: dropdown
    id: version
    attributes:
      label: Version of Zeneth
      description: What version of zeneth are you using?
      options:
       - v0.0.1
    validations:
      required: true
      
  - type: dropdown
    id: node-version
    attributes:
      label: Version of Node.js
      description: Also, what version of Node.js are you using? 
      options:
        - v18 (LTS)
        - v19
        - v20
    validations:
      required: true
      
  - type: textarea
    id: excepted
    attributes:
      label: Excepted Output
      description: Please describe your expectations the code you have tried.

  - type: textarea
    id: current
    attributes:
      label: Current Output
      description: Please describe your expectations the code you have tried.
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/AkaruiDevelopment/zeneth/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct 
          required: true
